
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-infra-alexeldeib-xyz-v1alpha1-bale
  failurePolicy: Fail
  name: mbale.kb.io
  rules:
  - apiGroups:
    - infra.alexeldeib.xyz
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - bales

---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-infra-alexeldeib-xyz-v1alpha1-bale
  failurePolicy: Fail
  name: vbale.kb.io
  rules:
  - apiGroups:
    - infra.alexeldeib.xyz
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - bales
