# permissions for end users to view bales.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bale-viewer-role
rules:
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - bales
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - bales/status
  verbs:
  - get
