# permissions for end users to edit bales.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bale-editor-role
rules:
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - bales
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - bales/status
  verbs:
  - get
