# permissions for end users to view hatchlings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hatchling-viewer-role
rules:
- apiGroups:
  - infra.alexeldeib.xyz
  resources:
  - hatchlings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infra.alexeldeib.xyz
  resources:
  - hatchlings/status
  verbs:
  - get
