# permissions for end users to edit hatchlings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hatchling-editor-role
rules:
- apiGroups:
  - infra.alexeldeib.xyz
  resources:
  - hatchlings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infra.alexeldeib.xyz
  resources:
  - hatchlings/status
  verbs:
  - get
