# permissions for end users to edit turtles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: turtle-editor-role
rules:
- apiGroups:
  - infra.alexeldeib.xyz
  resources:
  - turtles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infra.alexeldeib.xyz
  resources:
  - turtles/status
  verbs:
  - get
