# permissions for end users to view turtles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: turtle-viewer-role
rules:
- apiGroups:
  - infra.alexeldeib.xyz
  resources:
  - turtles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infra.alexeldeib.xyz
  resources:
  - turtles/status
  verbs:
  - get
