namePrefix: bale-

commonLabels:
  cluster.x-k8s.io/provider: "bale"

bases:
- crd
- webhook
- default

patchesJson6902:
- target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
    name: bales.infra.alexeldeib.xyz
  path: patch_crd_webhook_namespace.yaml
- target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
    name: turtles.infra.alexeldeib.xyz
  path: patch_crd_webhook_namespace.yaml

